version: '{build}'
image: ubuntu2004

skip_branch_with_pr: true
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
  - master
  - /release-.*/
  - /^\d+\.\d+\.\d+(-\S*)?$/

build_script:
- sh: ./build.sh

test: off
deploy: off
